apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-depl
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: api.internals
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-depl
            port:
              number: 80